/*
This class stores all the possible word cases within the string and stores a response to the script that the bot will reply to. 
It uses 2D arrays to store the data that the bot will sort through in order to find the proper case.
*/ 
const prompts = [
    // beginning of bot script (user replies to bot) hopefully the order
    ["im good", "im fine", "im great", "im decent", "im ok"], //1 Feeling Good
    ["im feeling bad", "im terrible", "im awful"],  //2 Feeling bad
    [""],//cannot expect prompt (name)  3
    [""],//cannot expect prompt (order number)  4
    ["happy with", "satisfied with", "pleased with", "works"],  //5 Happy   go to replies 11
    ["do not understand", "not working", "need repairs", "damaged", "does not work"],  //6 Confused/Broken  go to replies 6
    ["hate", "dislike","unhappy", "bad quality", "dissatisfied","unsatisfied",], //7 Unhappy    go to replies 10
    ["replace", "exchange"], //replace
    ["refund", "money back"],  //refund
    ["talk", "executive", "contact", "call", "chat"], // talk to an executive
    ["help", "help me", "assistance", "assist"], //help go to 15
    ["yes", "no"],  //premium customer, go to 12 if yes, go to 13 if no
    ["0, 1, 2, 3"], // bad rating
    ["yes", "no"], //file a complaint
    ["4", "5", "6"], // average rating
    ["7", "8", "9", "10"], // good rating

]



//Ideal script followed by any default replies
const replies = [
    
    // beginning of bot script (bot goes first here)

    //["Hi! Thank you for choosing our store. How are you doing today?"], Needs to be autogenerated, not in array
    
    ["I am glad to hear that! Could I please get your name?"],  //1 Feeling Good
    ["I am very sorry to hear that! Could I please get your name?"],  //2 Feeling bad
    //if either of these two cases are called, get name as variable, then call next array line^^ 
    ["Nice to meet you! Could you please enter the order number found on your receipt?"],  //3 name response
    //if this array function is called then call next array line^^
    ["How can we assist you with your product?"], //4 //order number response
    ["We're sorry to hear that this has occured, can you give more specific information about your problem?"], //6
    ["I am sorry that this product has given you trouble, could you please tell us further what is broken or confusing?"],  //7
    ["I am so sorry for your experience. Do you want a replacement, refund, or talk to an executive? Please pick one."],  //8
    ["Here's the form to request a replacement."], //replace
    ["Here's the form to request a refund."], //refund
    ["Here's the contact information of an executive you may contact between 10:00 AM to 4:00 PM PST."],  //talk to an executive
    ["Thank you for sharing your feedback. Hope you have a better experience next time!"],  //10 Unhappy
    ["We are happy to receive this positive feedback! Would you like to be our premium customer?"],  //11 premium customer
    ["Sounds good! Here's the form to fill to be a premium customer."],  //12 if yes
    ["That's okay. Maybe some other time."],  //13 if no
    ["Thank you for the feedback. Hope we can always serve you well!"],  //14 END
    ["What can we help you with? Please specify."], // 15 help   go to replace refund or talk to an executive if mention
    ["Sorry. Could you please explain in detail?"], // 16 no match  go to replace refund or talk to an executive if mention
    ["I'm sorry if we're not able to help you with your specific query. I could offer you a refund or a replacement for your order, or I could connect you to an executive."], //17
    ["Sorry we cannot help you with your specific query. Here are some FAQs you might want to look into."], //18 no match END
    ["How would you rate this conversation?"], //19
    ["We're so sorry, would you like to file a complaint?"], //bad rating
    ["Here's the form to file a complaint."], //if yes file a complaint, pretend user fills form
    ["We apologize for the inconvenience, thank you for using our services."] //bad rating after yes or no file complaint END
    ["Let us know how we can improve!"], //average rating pretend user fills form
    ["Thank you for letting us know!"], // average rating feedback END
    ["Thank you for using our service, we're glad we could be of service!"], //good rating END

]